### ISSUE TITLE
Copilot Studio helpers dir not copied on pip install and additional installation fixes

### ISSUE THREAD

**Issue by mbrg** [mbrg/power-pwn#74]
Trying to run `powerpwn copilot-studio-hunter deep-scan` I got the following error. This is because the directory `helpers` doesn't get created and its content not copied.

```bash
vscode ➜ /workspaces/power-pwn (install-all-prereqs) $ powerpwn copilot-studio-hunter deep-scan -d <domain> -tb 300


------------------------------------------------------------
                                                            
 _ __    ___  __      __  ___  _ __  _ __  __      __ _ __  
| '_ \  / _ \ \ \ /\ / / / _ \| '__|| '_ \ \ \ /\ / /| '_ \ 
| |_) || (_) | \ V  V / |  __/| |   | |_) | \ V  V / | | | |
| .__/  \___/   \_/\_/   \___||_|   | .__/   \_/\_/  |_| |_|
|_|                                 |_|                     

Hacker Summer Camp 2024 edition


------------------------------------------------------------


Domain:  zenitystage.com
2024-10-28 17:49:25 | root | INFO | Tenant ID: <tenantid>
2024-10-28 17:49:25 | root | INFO | Use the following URL to access the CoPilotStudio demo website: 
https://copilotstudio.microsoft.com/environments/Default-<tenantid>/bots/
2024-10-28 17:49:25 | root | INFO | Endpoint for the default environment bots schema: https://default<tenantid>.b3.environment.api.powerplatform.com/powervirtualagents/botsbyschema/
Checking if an existing solution publisher prefix value exists for this domain.
No existing solution publisher prefix value found for this domain, starting prefix scan.
Encountered error(s): 2 errors occured.
        * stat /home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/helpers/prefix_wordlist_char_fix_basic.txt: no such file or directory
        * stat /home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/helpers/suffix_wordlist_basic_1.txt: no such file or directory

Encountered error(s): 2 errors occured.
        * stat /home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/helpers/prefix_wordlist_char_fix_basic.txt: no such file or directory
        * stat /home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/helpers/suffix_wordlist_basic_1.txt: no such file or directory

Traceback (most recent call last):
  File "/home/vscode/.local/bin/powerpwn", line 8, in <module>
    sys.exit(main())
  File "/home/vscode/.local/lib/python3.8/site-packages/powerpwn/main.py", line 54, in main
    run_copilot_studio_command(args)
  File "/home/vscode/.local/lib/python3.8/site-packages/powerpwn/cli/runners.py", line 221, in run_copilot_studio_command
    DeepScan(args)
  File "/home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/modules/deep_scan.py", line 549, in __init__
    self.run()
  File "/home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/modules/deep_scan.py", line 737, in run
    for value, popen in get_ffuf_results_prefix(
  File "/home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/modules/deep_scan.py", line 416, in get_ffuf_results_prefix
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['ffuf', '-v', '-w', '/home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/helpers/prefix_wordlist_char_fix_basic.txt:FUZZ1', '-w', '/home/vscode/.local/lib/python3.8/site-packages/powerpwn/copilot_studio/helpers/suffix_wordlist_basic_1.txt:FUZZ2', '-u', 'https://default<tenantid>.b3.environment.api.powerplatform.com/powervirtualagents/botsbyschema/FUZZ1_FUZZ2/canvassettings?api-version=2022-03-01-preview', '-fr', '"demoWebsiteErrorCode": "404"', '-ac', '-rate', '0', '-t', '40', '-se', '-maxtime-job', '300', '-H', 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36', '-H', 'Accept: application/json, text/plain, */*', '-H', 'Accept-Language: en-US,en;q=0.5', '-H', 'Accept-Encoding: gzip, deflate, br, zstd', '-H', 'Origin: https://copilotstudio.microsoft.com', '-H', 'DNT: 1', '-H', 'Connection: keep-alive', '-H', 'Sec-Fetch-Dest: empty', '-H', 'Sec-Fetch-Mode: cors', '-H', 'Sec-Fetch-Site: cross-site', '-H', 'Sec-GPC: 1', '-H', 'Via: 1.1 103.230.38.175', '-H', 'TE: trailers']' returned non-zero exit status 1.
```

**Comment by AvishaiEZen** [comment]
Thanks. I suspect this might be related to the Python project file location not being set up correctly in some cases and so the helper files can't being located by FFUF (searching for them in an incorrec location) - will verify ASAP.

**Comment by AvishaiEZen** [comment]
1. Updating PPWN's package with the missing related helper files has been handled here: https://github.com/mbrg/power-pwn/pull/77/files
2. Adding additional related changes for improved installation as part of this issue:
  * Updated readme
  * Fixing missing __init__.py for the Power Pages module
  * Updating the init_repo.py 

The sum of these changes should hopefully resolve the issue reported here and other seen issues regarding the project's modules.
